### ISSUE TITLE
Improve print logs in this codebase

### ISSUE THREAD

**Issue by 0xf333** [ralyodio/dht_indexer#7]
## Description
We have multiple `console.log()` statements in our codebase for printing information about a discovered **infoHash** and the collected files. This creates redundancy.

### Example of the current format :
```
console.log('\n-----------------------------------------------\n');
console.log(`Discovered new infoHash:\n---> ${infoHash}\n`);
console.log('------------------------------------------------');
console.log(`${indentation(4)}>>> collected files: ${files.length} <<<`);
console.log('------------------------------------------------');
```

<br>

## Desired Improvement
Refactor the print logs by using a single `console.log()` statement instead of multiple.

### Example of the desired format:
```
console.log(
    '\n-----------------------------------------------\n'+
    `\nDiscovered new infoHash:\n---> ${infoHash}\n`+
    '\n------------------------------------------------\n' +
    `${indentation(4)}>>> collected files: ${files.length} <<<\n` +
    '------------------------------------------------'
);
```

---

## Task Summary/checklist
- [ ] Only work on print logs for this ticket.
- [ ] Do not edit anything else, aside from print logs.
- [ ] Test your changes to make sure that they are working as intended before submitting your pull request.
- [ ] Tag me in your pull request so I can review it.

**Comment by Leifen09** [comment]
I would like to work on this issue, could you please assign it to me? @0xf333

**Comment by 0xf333** [comment]
> I would like to work on this issue, could you please assign it to me? @0xf333

@Leifen09 

![Screenshot from 2024-02-19 05-26-39](https://github.com/ralyodio/dht_indexer/assets/100840345/667c135a-c1d0-4667-ad55-54f885b372ca)

**Comment by 0xf333** [comment]
closed by #9
